version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: jobparser
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=jobparser
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:
